(
    (PRINT (CONS '1' (CONS '2' NIL)))
)

#   this->word[this->currentrow++][0] = '(';
#   this->word[this->currentrow++][0] = '(';
#   strcpy(this->word[this->currentrow++], "PRINT");
#   strcpy(this->word[this->currentrow++], "(");
#   strcpy(this->word[this->currentrow++], "CONS");
#   strcpy(this->word[this->currentrow++], "'1'");
#   strcpy(this->word[this->currentrow++], "(");
#   strcpy(this->word[this->currentrow++], "CONS");
#   strcpy(this->word[this->currentrow++], "'2'");
#   strcpy(this->word[this->currentrow++], "NIL");
#   strcpy(this->word[this->currentrow++], ")");
#   strcpy(this->word[this->currentrow++], ")");
#   strcpy(this->word[this->currentrow++], ")");
#   strcpy(this->word[this->currentrow++], ")");
