(
   (WHILE (LESS '1' '2') ((PRINT "LOOP FOREVER")) )
)

(
(
WHILE
(
LESS
'1'
'2'
)
(
(
PRINT
\"LOOP FOREVER\"
)
)
)
)

   strcpy(this->word[this->currentrow++], "(");
   strcpy(this->word[this->currentrow++], "(");
   strcpy(this->word[this->currentrow++], "WHILE");
   strcpy(this->word[this->currentrow++], "(");
   strcpy(this->word[this->currentrow++], "LESS");
   strcpy(this->word[this->currentrow++], "'1'");
   strcpy(this->word[this->currentrow++], "'2'");
   strcpy(this->word[this->currentrow++], ")");
   strcpy(this->word[this->currentrow++], "(");
   strcpy(this->word[this->currentrow++], "(");
   strcpy(this->word[this->currentrow++], "PRINT");
   strcpy(this->word[this->currentrow++], ""LOOP FOREVER"");
   strcpy(this->word[this->currentrow++], ")");
   strcpy(this->word[this->currentrow++], ")");
   strcpy(this->word[this->currentrow++], ")");
   strcpy(this->word[this->currentrow++], ")");

